import { homedir } from "os";
import { join } from "path";
import { PlacementStore } from "./placements";
import { makeRemoteSessionId, parseRemoteSessionId, sanitizeSafeAgentEvent, sanitizeSafeWebState, type WorkerCommand } from "./types";
import { WorkerClient, WorkerRegistry } from "./worker-client";
import { WebRpcError } from "../rpc-manager";
let registry:WorkerRegistry|undefined,store:PlacementStore|undefined;
export function getPorbsRegistry(){return registry??=WorkerRegistry.fromEnvironment();}
export function getPlacementStore(){return store??=new PlacementStore(process.env.PORBS_PLACEMENTS_PATH??join(homedir(),".omp","porbs","placements.json"));}
export function resetPorbsControllerForTests(){registry=undefined;store=undefined;}
export function isRemoteSessionId(id:string){try{parseRemoteSessionId(id);return true;}catch{return false;}}
function closed(value:Record<string,unknown>,keys:string[]){if(Object.keys(value).some(key=>!keys.includes(key)))throw new WebRpcError("Invalid remote command","invalid_remote_command");}
export async function createRemoteSession(body:Record<string,unknown>){if(body.remote!==true)return undefined;closed(body,["cwd","type","message","remote","operationId"]);if(body.type!=="prompt"&&body.type!=="ensure_session"||body.type==="prompt"&&typeof body.message!=="string"||typeof body.operationId!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(body.operationId))throw new WebRpcError("Invalid remote create command","invalid_remote_command");const target=getPorbsRegistry().first();if(!target)throw new WebRpcError("No remote worker configured","worker_not_configured");const operationId=body.operationId,id=makeRemoteSessionId(target.hostId,operationId),placement=await getPlacementStore().createPending(id,target.hostId,target.workspaceId),client=new WorkerClient(target);try{const created=await client.create(id,operationId);let active=placement;if(placement.lifecycle==="creating"||placement.lifecycle==="failed")active=await getPlacementStore().compareAndSet(id,placement.revision,{lifecycle:"active"});let data:unknown=null;if(body.type==="prompt")data=(await client.send(id,created.session.revision,{type:"prompt",message:body.message as string},operationId)).result;return {sessionId:id,data,placement:active};}catch(error){const current=await getPlacementStore().get(id);if(current&&current.lifecycle==="creating")await getPlacementStore().compareAndSet(id,current.revision,{lifecycle:"failed"});throw error;}}
export async function remoteState(id:string){const parsed=parseRemoteSessionId(id),placement=await getPlacementStore().get(parsed.id);if(!placement)return undefined;const target=getPorbsRegistry().resolve(placement.hostId);if(!target)throw new WebRpcError("Worker not configured","worker_not_configured");const response=await new WorkerClient(target).getState(parsed.id);response.state=sanitizeSafeWebState(response.state);const lifecycle=response.session.lifecycle;const desired=lifecycle==="stopped"?"stopped":lifecycle==="failed"?"failed":lifecycle==="ready"||lifecycle==="running"?"active":placement.lifecycle;if(desired!==placement.lifecycle)await getPlacementStore().compareAndSet(parsed.id,placement.revision,{lifecycle:desired});return response;}
export async function remoteCommand(id:string,body:Record<string,unknown>){const parsed=parseRemoteSessionId(id),placement=await getPlacementStore().get(parsed.id);if(!placement)throw new WebRpcError("Session not found","session_not_found");const target=getPorbsRegistry().resolve(placement.hostId);if(!target)throw new WebRpcError("Worker not configured","worker_not_configured");let command:WorkerCommand;if(body.type==="prompt"){closed(body,["type","message","operationId"]);if(typeof body.message!=="string"||typeof body.operationId!=="string"||!/[0-9a-f-]{36}/.test(body.operationId))throw new WebRpcError("Invalid prompt","invalid_remote_command");command={type:"prompt",message:body.message};}else if(body.type==="abort"){closed(body,["type","operationId"]);if(typeof body.operationId!=="string"||!/[0-9a-f-]{36}/.test(body.operationId))throw new WebRpcError("Invalid operation","invalid_remote_command");command={type:"abort"};}else throw new WebRpcError("Remote command not supported","remote_command_not_supported");const state=await new WorkerClient(target).getState(parsed.id);try{return await new WorkerClient(target).send(parsed.id,state.session.revision,command,body.operationId as string);}catch(error){throw new WebRpcError(error instanceof Error?error.message:"Remote command failed",error instanceof Error&&error.message.includes("conflict")?"revision_conflict":"remote_command_failed");}}
export async function stopRemoteSession(id:string){const parsed=parseRemoteSessionId(id),placement=await getPlacementStore().get(parsed.id);if(!placement)throw new WebRpcError("Session not found","session_not_found");const target=getPorbsRegistry().resolve(placement.hostId);if(!target)throw new WebRpcError("Worker not configured","worker_not_configured");const state=await new WorkerClient(target).getState(parsed.id),stopping=await getPlacementStore().compareAndSet(parsed.id,placement.revision,{lifecycle:"stopping"});const result=await new WorkerClient(target).stop(parsed.id,state.session.revision,parsed.uuid);await getPlacementStore().compareAndSet(parsed.id,stopping.revision,{lifecycle:"stopped"});return result;}
export async function remotePlacements(){return getPlacementStore().list();}
export async function remoteEventsResponse(id:string,request:Request){const parsed=parseRemoteSessionId(id),placement=await getPlacementStore().get(parsed.id);if(!placement)return new Response("Session not found",{status:404});const target=getPorbsRegistry().resolve(placement.hostId);if(!target)return new Response("Worker not configured",{status:503});const cursor=request.headers.get("last-event-id"),parts=cursor?.split(":");let upstream:Response;try{upstream=await new WorkerClient(target).events(parsed.id,parts?.[0]??null,Number(parts?.[1]??0),request.signal);}catch(error){const missing=error instanceof Error&&error.message==="session_not_found";return new Response(missing?"Session not found":"Worker stream unavailable",{status:missing?404:502});}if(upstream.headers.get("content-type")?.split(";")[0]!=="text/event-stream")return new Response("Invalid worker stream",{status:502});const decoder=new TextDecoder(),encoder=new TextEncoder();let buffer="",lastSeq=Number(parts?.[1]??0),streamId=parts?.[0]??null;const transformed=upstream.body!.pipeThrough(new TransformStream<Uint8Array,Uint8Array>({transform(chunk,controller){buffer+=decoder.decode(chunk,{stream:true});if(buffer.length>300_000)throw new Error("worker_event_too_large");for(;;){const end=buffer.indexOf("\n\n");if(end<0)break;const block=buffer.slice(0,end);buffer=buffer.slice(end+2);if(block.startsWith(":")){controller.enqueue(encoder.encode(":\n\n"));continue;}const idLine=block.split("\n").find(line=>line.startsWith("id: ")),dataLine=block.split("\n").find(line=>line.startsWith("data: "));if(!dataLine)continue;const record=JSON.parse(dataLine.slice(6)) as Record<string,unknown>;if(idLine){const [nextStream,nextSeqRaw]=idLine.slice(4).split(":"),nextSeq=Number(nextSeqRaw),event=sanitizeSafeAgentEvent(record.event);if(record.v!==1||record.sessionId!==parsed.id||record.streamId!==nextStream||record.seq!==nextSeq||!Number.isSafeInteger(nextSeq)||nextSeq<=lastSeq||streamId!==null&&streamId!==nextStream)throw new Error("invalid_worker_event");streamId=nextStream;lastSeq=nextSeq;controller.enqueue(encoder.encode(`id: ${idLine.slice(4)}\ndata: ${JSON.stringify(event)}\n\n`));}else if(record.type==="connected"&&record.reset===true&&typeof record.streamId==="string"){streamId=record.streamId;lastSeq=0;controller.enqueue(encoder.encode(`data: ${JSON.stringify({type:"connected",sessionId:parsed.id,reset:true})}\n\n`));}else throw new Error("invalid_worker_event");}}}));return new Response(transformed,{headers:{"Content-Type":"text/event-stream","Cache-Control":"no-store, no-transform",Connection:"keep-alive"}});}
