import { createServer, type Server } from "http";
import { parseRemoteSessionId, type EventRecord, type WorkerCommand } from "./types";
import { WorkerAuthenticator } from "./worker-auth";
import { WorkerSessionManager } from "./worker-sessions";
const MAX_BODY=1_100_000,MAX_SUBSCRIBERS=8,MAX_GLOBAL_SUBSCRIBERS=64;
let globalSubscribers=0;
function exact(value:unknown,keys:string[]){if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value).some(k=>!keys.includes(k)))throw new Error("invalid_request");return value as Record<string,unknown>;}
const PUBLIC_ERRORS=new Set(["unauthorized","invalid_request","invalid_command","invalid_cursor","invalid_operation_id","body_too_large","not_found","session_not_found","revision_conflict","operation_conflict","operation_indeterminate","unknown_workspace","wrong_host","too_many_subscribers"]);
export function createWorkerServer(options:{auth:WorkerAuthenticator;manager:WorkerSessionManager}):Server{return createServer(async(req,res)=>{try{const url=new URL(req.url??"/","http://127.0.0.1"),method=req.method??"GET",chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)throw new Error("body_too_large");chunks.push(chunk);}const body=Buffer.concat(chunks),headers=new Headers();for(const [k,v]of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(","):v);let parsed:Record<string,unknown>={};if(body.length)parsed=exact(JSON.parse(body.toString("utf8")),["v","operationId","workspaceId","expectedRevision","command"]);const operationId=typeof parsed.operationId==="string"?parsed.operationId:headers.get("x-omp-operation-id")??"";if(!/^[0-9a-f-]{36}$/.test(operationId))throw new Error("invalid_operation_id");await options.auth.verify(method,url.pathname+url.search,body,headers,operationId);const match=/^\/v1\/sessions\/([^/]+)(?:\/(commands|events))?$/.exec(url.pathname);if(!match)throw new Error("not_found");const id=parseRemoteSessionId(decodeURIComponent(match[1])).id;let status=200,data:unknown;
if(method==="PUT"&&!match[2]){exact(parsed,["v","operationId","workspaceId"]);if(parsed.v!==1)throw new Error("invalid_request");data={v:1,operationId,session:await options.manager.create(id,parsed.workspaceId as string,operationId)};status=201;}
else if(method==="GET"&&!match[2]){const found=await options.manager.state(id);data={v:1,session:found.projection,state:found.state};}
else if(method==="POST"&&match[2]==="commands"){exact(parsed,["v","operationId","expectedRevision","command"]);const command=exact(parsed.command,["type","message"]);if(command.type!=="prompt"&&command.type!=="abort"||command.type==="abort"&&"message"in command)throw new Error("invalid_command");data=await options.manager.command(id,operationId,parsed.expectedRevision as number,command as unknown as WorkerCommand);}
else if(method==="DELETE"&&!match[2]){exact(parsed,["v","operationId","expectedRevision"]);data=await options.manager.stop(id,operationId,parsed.expectedRevision as number);}
else if(method==="GET"&&match[2]==="events"){const after=Number(url.searchParams.get("after")??"0");if(!Number.isSafeInteger(after)||after<0)throw new Error("invalid_cursor");const found=options.manager.events(id,url.searchParams.get("streamId"),after);if(found.internal.listeners.size>=MAX_SUBSCRIBERS||globalSubscribers>=MAX_GLOBAL_SUBSCRIBERS)throw new Error("too_many_subscribers");globalSubscribers++;let cleaned=false;const heartbeat=setInterval(()=>{if(!res.write(":\n\n"))cleanup();},15_000);const writeRecord=(record:EventRecord)=>{if(!res.write(`id: ${record.streamId}:${record.seq}\ndata: ${JSON.stringify(record)}\n\n`))cleanup();};const cleanup=()=>{if(cleaned)return;cleaned=true;globalSubscribers--;clearInterval(heartbeat);found.internal.listeners.delete(writeRecord);res.end();};res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-store, no-transform",Connection:"keep-alive"});if(found.reset&&!res.write(`data: ${JSON.stringify({type:"connected",sessionId:id,reset:true,streamId:found.internal.projection.streamId})}\n\n`))cleanup();for(const record of found.records){if(cleaned)break;writeRecord(record);}if(cleaned)return;found.internal.listeners.add(writeRecord);req.once("close",cleanup);return;}else throw new Error("not_found");res.writeHead(status,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify(data));}catch(error){const raw=error instanceof Error?error.message:"internal_error",message=PUBLIC_ERRORS.has(raw)?raw:"worker_error",status=message==="unauthorized"?401:message==="not_found"||message==="session_not_found"?404:message.includes("conflict")||message==="operation_indeterminate"?409:message==="too_many_subscribers"?429:400;res.writeHead(status,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify({error:message}));}});}
